### ISSUE TITLE
Stats after games

### ISSUE THREAD

**Issue by Slurpas** [aiarena/local-play-bootstrap#2]
Hi,

I'd like to request "stats"/summary after running multiple games.
So in other words, if u run 100 matches, id like to know as an example that Bot_1 won 67 games and Bot_2 won 33 games of that 100.
Results seems to only show the last game so either to store all games in a log-file or log a summary of all games in a run would be very nice.

**Comment by lladdy** [comment]
Thanks for reporting @Slurpas 
I have created an issue here regarding the arenaclient results file not retaining all the results: https://github.com/aiarena/aiarena-client/issues/58

**Comment by ratosh** [comment]
Possibly solved with #5. At the end of a run you get a final stats like this (only show winners):
| Bot                | Wins |
|--------------------|------|
| basic_bot          | 10   |

**Comment by ratosh** [comment]
Improved stats:
| Bot                          | Elo      | Wins | Losses | Ties |
|------------------------------|----------|------|--------|------|
| Sajuuk                       | 999 ±0   | 2    | 0      | 0    |
| TyrT                         | 999 ±0   | 2    | 0      | 0    |
| Caninana                     | 999 ±0   | 2    | 0      | 0    |
| SharkyProtossExampleBot      | 999 ±0   | 2    | 0      | 0    |
| QueenBot                     | 0   ±999 | 1    | 1      | 0    |
| SharkyTerranExampleBot       | 0   ±999 | 1    | 1      | 0    |
| Ender                        | -88 ±198 | 6    | 10     | 0    |
| SaShaBot                     | -999±0   | 0    | 2      | 0    |
| Chaosbot                     | -999±0   | 0    | 2      | 0    |

**Comment by lladdy** [comment]
Looks like this is resolved by #5 - closing.
